[Autologin]
Relogin=false
Session=plasma
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Theme]
Current=sddm-astronaut-theme

[Users]
MaximumUid=60000
MinimumUid=1000
