# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ THEME: Cyber Hacker (Ultra-Deep Dark OLED)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Basic Colors
foreground              #e6edf3
background              #07080c
selection_foreground    #ffffff
selection_background    #1e293b

# Cursor Colors
cursor                  #00f5d4
cursor_text_color       #07080c

# URL Underline
url_color               #00f5d4

# Window Borders
active_border_color     #00f5d4
inactive_border_color   #1e2430
bell_border_color       #ff5572

# Titlebar
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab Bar
tab_bar_background      #040508
active_tab_foreground   #07080c
active_tab_background   #00f5d4
inactive_tab_foreground #8b949e
inactive_tab_background #12151e

# Mark Colors
mark1_foreground        #07080c
mark1_background        #00f5d4
mark2_foreground        #07080c
mark2_background        #f6c177
mark3_foreground        #07080c
mark3_background        #ff5572

# The 16 Terminal Colors
# Black
color0                  #161922
color8                  #484f58

# Red
color1                  #ff5572
color9                  #ff7b92

# Green
color2                  #26d07c
color10                 #3ae38f

# Yellow
color3                  #f6c177
color11                 #ffcf85

# Blue
color4                  #58a6ff
color12                 #79b8ff

# Magenta
color5                  #bc8cff
color13                 #d2a8ff

# Cyan
color6                  #00f5d4
color14                 #5eead4

# White
color7                  #d2d7df
color15                 #ffffff
