# Basic colors
foreground              #eae0e7
background              #171217
selection_foreground    #f3dbf2
selection_background    #524153

# Cursor colors
cursor                  #e9b5ef
cursor_text_color       #472150

# URL underline color when hovering with mouse
url_color               #f5b7b0

# Kitty window border colors
active_border_color     #e9b5ef
inactive_border_color   #4d444c
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #fdd6ff
active_tab_background   #603768
inactive_tab_foreground #cfc3cd
inactive_tab_background #231e23
tab_bar_background      #171217

# Colors for marks
mark1_foreground #472150
mark1_background #e9b5ef
mark2_foreground #3a2b3c
mark2_background #d6c0d6
mark3_foreground #4c2521
mark3_background #f5b7b0

# The 16 terminal colors
# black
color0 #4d444c
color8 #988d97

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #e9b5ef
color10 #fdd6ff

# yellow
color3  #f5b7b0
color11 #ffdad5

# blue
color4  #d6c0d6
color12 #f3dbf2

# magenta
color5  #603768
color13 #794f81

# cyan
color6  #524153
color14 #673b36

# white
color7  #cfc3cd
color15 #eae0e7
