#!/usr/bin/env bash
# Monitor Modes & Presets Switcher for Hyprland

ACTION="$1"
ARG2="$2"
ARG3="$3"

MONITORS_JSON=$(hyprctl monitors all -j 2>/dev/null || echo "[]")
MON_CONF="$HOME/.config/hypr/config/monitors.conf"

# Identify internal (eDP) and external monitors
INTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.name | test("eDP|LVDS|DSI")) | .name' | head -n1)
EXTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.name | test("eDP|LVDS|DSI") | not) | .name' | head -n1)

# Fallback if names are different
[ -z "$INTERNAL" ] && INTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[0].name // "eDP-1"')
[ -z "$EXTERNAL" ] && EXTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[1].name // "HDMI-A-1"')

# Fetch preferred or current modes
INT_RES=$(echo "$MONITORS_JSON" | jq -r --arg n "$INTERNAL" '.[] | select(.name==$n) | "\(.width)x\(.height)@\(.refreshRate | round)"' | head -n1)
EXT_RES=$(echo "$MONITORS_JSON" | jq -r --arg n "$EXTERNAL" '.[] | select(.name==$n) | "\(.width)x\(.height)@\(.refreshRate | round)"' | head -n1)

[ -z "$INT_RES" ] || [ "$INT_RES" == "0x0@0" ] && INT_RES="1920x1080@120"
[ -z "$EXT_RES" ] || [ "$EXT_RES" == "0x0@0" ] && EXT_RES="1920x1080@144"

move_workspaces() {
    local target_mon="$1"
    for i in {1..10}; do
        hyprctl dispatch moveworkspacetomonitor "$i" "$target_mon" >/dev/null 2>&1
    done
}

save_and_apply() {
    local batch_cmd="$1"
    local conf_content="$2"
    local target_mon_to_move_to="$3"
    
    # Save persistently to monitors.conf
    cat << MCONF > "$MON_CONF"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MONITORS (Auto-Generated by Monitor Manager)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$(echo -e "$conf_content")
MCONF

    if [ -n "$target_mon_to_move_to" ]; then
        if [ "$ACTION" == "only-external" ]; then
            hyprctl keyword monitor "$EXTERNAL, $EXT_RES, 0x0, 1.0" >/dev/null 2>&1
            sleep 0.5
        elif [ "$ACTION" == "only-internal" ]; then
            hyprctl keyword monitor "$INTERNAL, $INT_RES, 0x0, 1.0" >/dev/null 2>&1
            sleep 0.5
        fi
        
        move_workspaces "$target_mon_to_move_to"
    fi

    # Apply to Hyprland runtime immediately
    hyprctl --batch "$batch_cmd" >/dev/null 2>&1
    
    # Reload wallpaper daemon to span/adjust layers
    (swww kill 2>/dev/null ; sleep 0.2 ; swww-daemon 2>/dev/null &) &
}

case "$ACTION" in
    "only-external")
        if [ -n "$EXTERNAL" ]; then
            CMD="keyword monitor $EXTERNAL, $EXT_RES, 0x0, 1.0 ; keyword monitor $INTERNAL, disable"
            CONF="monitor = $INTERNAL, disable\nmonitor = $EXTERNAL, $EXT_RES, 0x0, 1.0"
            save_and_apply "$CMD" "$CONF" "$EXTERNAL"
            notify-send -i "video-display" "Display Mode" "Active: External Screen Only ($EXTERNAL)" -u low
        fi
        ;;

    "only-internal")
        if [ -n "$INTERNAL" ]; then
            CMD="keyword monitor $INTERNAL, $INT_RES, 0x0, 1.0 ; keyword monitor $EXTERNAL, disable"
            CONF="monitor = $EXTERNAL, disable\nmonitor = $INTERNAL, $INT_RES, 0x0, 1.0"
            save_and_apply "$CMD" "$CONF" "$INTERNAL"
            notify-send -i "video-display" "Display Mode" "Active: Laptop Screen Only ($INTERNAL)" -u low
        fi
        ;;

    "mirror")
        if [ -n "$INTERNAL" ] && [ -n "$EXTERNAL" ]; then
            CMD="keyword monitor $INTERNAL, $INT_RES, 0x0, 1.0 ; keyword monitor $EXTERNAL, preferred, auto, 1.0, mirror, $INTERNAL"
            CONF="monitor = $INTERNAL, $INT_RES, 0x0, 1.0\nmonitor = $EXTERNAL, preferred, auto, 1.0, mirror, $INTERNAL"
            save_and_apply "$CMD" "$CONF"
            notify-send -i "video-display" "Display Mode" "Active: Mirror / Clone Displays" -u low
        fi
        ;;

    "extend-left"|"extend")
        # External on Left (0x0), Laptop on Right (1920x0)
        if [ -n "$INTERNAL" ] && [ -n "$EXTERNAL" ]; then
            CMD="keyword monitor $EXTERNAL, $EXT_RES, 0x0, 1.0 ; keyword monitor $INTERNAL, $INT_RES, 1920x0, 1.0"
            CONF="monitor = $EXTERNAL, $EXT_RES, 0x0, 1.0\nmonitor = $INTERNAL, $INT_RES, 1920x0, 1.0"
            save_and_apply "$CMD" "$CONF"
            notify-send -i "video-display" "Display Mode" "Active: Extended Display (External Left)" -u low
        fi
        ;;

    "extend-right")
        # Laptop on Left (0x0), External on Right (1920x0)
        if [ -n "$INTERNAL" ] && [ -n "$EXTERNAL" ]; then
            CMD="keyword monitor $INTERNAL, $INT_RES, 0x0, 1.0 ; keyword monitor $EXTERNAL, $EXT_RES, 1920x0, 1.0"
            CONF="monitor = $INTERNAL, $INT_RES, 0x0, 1.0\nmonitor = $EXTERNAL, $EXT_RES, 1920x0, 1.0"
            save_and_apply "$CMD" "$CONF"
            notify-send -i "video-display" "Display Mode" "Active: Extended Display (External Right)" -u low
        fi
        ;;

    "extend-top")
        # External Above Laptop
        if [ -n "$INTERNAL" ] && [ -n "$EXTERNAL" ]; then
            CMD="keyword monitor $EXTERNAL, $EXT_RES, 0x0, 1.0 ; keyword monitor $INTERNAL, $INT_RES, 0x1080, 1.0"
            CONF="monitor = $EXTERNAL, $EXT_RES, 0x0, 1.0\nmonitor = $INTERNAL, $INT_RES, 0x1080, 1.0"
            save_and_apply "$CMD" "$CONF"
            notify-send -i "video-display" "Display Mode" "Active: Extended Display (External Top)" -u low
        fi
        ;;

    "toggle")
        TARGET_MON="$ARG2"
        if [ -n "$TARGET_MON" ]; then
            IS_DISABLED=$(echo "$MONITORS_JSON" | jq -r --arg n "$TARGET_MON" '.[] | select(.name==$n) | .disabled')
            if [ "$IS_DISABLED" == "true" ]; then
                # Enable it
                RES=$(echo "$MONITORS_JSON" | jq -r --arg n "$TARGET_MON" '.[] | select(.name==$n) | "\(.availableModes[0] // "preferred")"')
                hyprctl keyword monitor "$TARGET_MON, preferred, auto, 1.0" >/dev/null 2>&1
                notify-send -i "video-display" "Monitor Enabled" "$TARGET_MON turned ON" -u low
            else
                # Disable it
                hyprctl keyword monitor "$TARGET_MON, disable" >/dev/null 2>&1
                notify-send -i "video-display" "Monitor Disabled" "$TARGET_MON turned OFF" -u low
            fi
        fi
        ;;

    "get-mode")
        # Detect current profile
        HAS_DISABLED=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.disabled==true) | .name' | head -n1)
        HAS_MIRROR=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.mirrorOf!="none" and .mirrorOf!="") | .name' | head -n1)
        
        if [ -n "$HAS_MIRROR" ]; then
            echo "mirror"
        elif [ "$HAS_DISABLED" == "$INTERNAL" ]; then
            echo "only-external"
        elif [ "$HAS_DISABLED" == "$EXTERNAL" ] || [ -z "$EXTERNAL" ]; then
            echo "only-internal"
        elif [ -n "$EXTERNAL" ] && [ -n "$INTERNAL" ]; then
            EXT_X=$(echo "$MONITORS_JSON" | jq -r --arg n "$EXTERNAL" '.[] | select(.name==$n) | .x')
            INT_X=$(echo "$MONITORS_JSON" | jq -r --arg n "$INTERNAL" '.[] | select(.name==$n) | .x')
            EXT_Y=$(echo "$MONITORS_JSON" | jq -r --arg n "$EXTERNAL" '.[] | select(.name==$n) | .y')
            INT_Y=$(echo "$MONITORS_JSON" | jq -r --arg n "$INTERNAL" '.[] | select(.name==$n) | .y')
            
            # Use jq defaults in case they are null for some reason
            [ -z "$EXT_X" ] || [ "$EXT_X" == "null" ] && EXT_X=0
            [ -z "$INT_X" ] || [ "$INT_X" == "null" ] && INT_X=0
            [ -z "$EXT_Y" ] || [ "$EXT_Y" == "null" ] && EXT_Y=0
            [ -z "$INT_Y" ] || [ "$INT_Y" == "null" ] && INT_Y=0

            if [ "$EXT_Y" -lt "$INT_Y" ] && [ "$EXT_Y" != "$INT_Y" ]; then
                echo "extend-top"
            elif [ "$EXT_X" -lt "$INT_X" ]; then
                echo "extend-left"
            else
                echo "extend-right"
            fi
        else
            echo "single"
        fi
        ;;
esac
