splash = false
ipc = on

preload = /home/hero/Pictures/Wallpapers/images/mountain_sunset.png

wallpaper = eDP-1,/home/hero/Pictures/Wallpapers/images/mountain_sunset.png

wallpaper {
    monitor = eDP-1
    path = /home/hero/Pictures/Wallpapers/images/mountain_sunset.png
    fit_mode = cover
}
