# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ THEME: Vesper (Pitch Black OLED Minimalist)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

foreground              #ffffff
background              #000000
selection_foreground    #000000
selection_background    #ebb58c

# Cursor
cursor                  #ebb58c
cursor_text_color       #000000

# URL
url_color               #ebb58c

# Window Borders
active_border_color     #ebb58c
inactive_border_color   #222222
bell_border_color       #ff6600

# Tab Bar
tab_bar_background      #000000
active_tab_foreground   #000000
active_tab_background   #ebb58c
inactive_tab_foreground #888888
inactive_tab_background #111111

# The 16 Terminal Colors
# Black
color0                  #181818
color8                  #444444

# Red
color1                  #ff5555
color9                  #ff6e6e

# Green
color2                  #50fa7b
color10                 #69ff94

# Yellow
color3                  #ebb58c
color11                 #ffd2a6

# Blue
color4                  #65b2ff
color12                 #8ec5fc

# Magenta
color5                  #d18eff
color13                 #e2b4ff

# Cyan
color6                  #65e6e0
color14                 #9df0ec

# White
color7                  #e0e0e0
color15                 #ffffff
