Net/ThemeName "adw-gtk3-dark"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Gtk/CursorThemeSize 24
Net/IconThemeName "candy-icons"
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/SoundThemeName "ocean"
Gtk/FontName "Noto Sans,  10"
Net/CursorBlink 1
Net/CursorBlinkTime 1000
Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
