# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ WINDOW & LAYER RULES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ─────────────────────────────
# Layer rules (OSD / overlays)
# ─────────────────────────────
layerrule = match:namespace = volume_osd, no_anim = on
layerrule = match:namespace = brightness_osd, no_anim = on
layerrule = match:namespace = hyprpicker, no_anim = on
layerrule = match:namespace = qsdock, no_anim = on
layerrule = match:namespace = ext-session-lock, blur = on
layerrule = match:namespace = ext-session-lock, ignore_alpha 0.2

# ─────────────────────────────
# Window rules
# ─────────────────────────────

# ───────── CS2 ─────────
windowrule = match:class = cs2, immediate = on
windowrule = match:class = cs2, keep_aspect_ratio = on

# ───────── App Launcher ─────────
windowrule = match:title = app-launcher, float = on
windowrule = match:title = app-launcher, center = on
windowrule = match:title = app-launcher, size = 1200 600
windowrule = match:title = app-launcher, animation = slide

# ───────── Polkit Authentication Agent ─────────
windowrule = match:class = .*polkit-kde.*, float = on
windowrule = match:class = .*polkit-kde.*, center = on
windowrule = match:class = .*polkit-kde.*, dim_around = on

# ───────── Kitty Terminal ─────────
windowrule = match:class = kitty, opacity 0.94 0.88
windowrule = match:class = kitty, rounding 12

windowrule = match:class = .*shortcut.*, float = on
windowrule = match:class = .*shortcut.*, center = on
windowrule = match:class = .*shortcut.*, size = 950 680
windowrule = match:initial_class = .*shortcut.*, float = on
windowrule = match:initial_class = .*shortcut.*, center = on
windowrule = match:title = .*shortcut.*, float = on
windowrule = match:title = .*shortcut.*, center = on




